Feature static link lib download script
XadillaX/rocketmq-client-nodejs pull request #2
Opened 2018-11-28 04:34 UTC by frayds

add one function on downloading different files according to user's OS

2018-11-28 04:59 UTC, XadillaX commented
some directories:

1. Linux: static library downloads to deps/llibrocketmq.a
2. macOS: dynamic library downloads to deps/librocketmq.dylib
3. Windows: dynamic and static libraries download to deps/rocketmq-client-cpp.{dll,lib}

2018-11-28 05:01 UTC, XadillaX commented
/cc @duanpengfei

2018-11-28 08:28 UTC, XadillaX requested changes
Some nits submitted.

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +const ENVIRONMENT = process.env.npm_lifecycle_event;
`"use strict"`

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +if(ENVIRONMENT === "build") {
This script is certainly running under `postinstall`.

These `if` states is necessary
.

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +const ENVIRONMENT = process.env.npm_lifecycle_event;
ps. filename use underscore: script/lib_download.js

Because macOS is dynamic library.

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +    const httpclient = require("urllib").create();
```js
const urllib = require("urllib");

urllib.request(...);
```

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +    // 操作系统类型,返回值有'darwin', 'freebsd', 'linux', 'sunos' , 'win32'
Use English comment.

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +    if(osType === "win32") {
IMHO, we can modify it like:

```js
const pkg = require("../package");

const MIRROR_ROOT = "https://oss.../";
const OS_MAP = {
  macOS: "/something/like/librocketmq.dylib",
  linux: "..."
};
const version = pkg.cppSDKVersion;

const url = `MIRROR_ROOT/${version}${OS_MAP[osType]}`;
urllib.request(url, ...);
```

And then add a column named `cppSDKVersion` in package.json to specify the version.

If error occurred, we should `process.exit(4)`.

2018-11-28 08:28 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +    if(osType === "win32") {
btw, use English comment.

2018-11-29 02:35 UTC, frayds commented on script/staticLinkLibDownload.js
> +if(ENVIRONMENT === "build") {
```suggestion
if(ENVIRONMENT === "build") {
```
excuse me, i am still a little bit confused about what u said, could u please explain more, thanks.
as i understand, the lib must be downloaded before the `build` process and after `install` process, so i write the code in the `postInstall` process. why u said the `build` if states is necessary ?

2018-11-29 15:40 UTC, XadillaX commented on script/staticLinkLibDownload.js
> +if(ENVIRONMENT === "build") {
Sorry, these `if` states are not necessary. You can consider that this script is certainly running under `postInstall`.

2018-12-03 05:02 UTC, XadillaX commented on script/lib_download.js
> +if(ENVIRONMENT === "postinstall") {
we don't need `if` here.

2018-12-03 05:13 UTC, XadillaX requested changes
```javascript
        httpclient.request(fileURL, {
            timeout: 1000000
        }, (err, data) => {
            if(err) {
                process.exit(4);
                throw err;
            }
            fs.writeFile(filePath, data, error => {
                if(error) {
                    process.exit(4);
                }
            });
        });
```
Code above is redundant.

```javascript
var Scarlet = require("scarlet-task");
var scarlet = new Scarlet(2);

function getUrlMap(callback) {
    const urlMap = [];
    switch(osType) {
    case "win32":
        urlMap.push(<dll>);
        urlMap.push(<lib>);
        process.nextTick(() => { callback(undefined, urlMap); });
        break;
    }

    case "darwin": {
        urlMap.push(<dylib>);
        process.nextTick(() => { callback(undefined, urlMap); });
        break;
    }

    case "linux": {
        osInfo.then(...);
        break;
    }

    default: process.nextTick(() => { callback(new Error('...')); });
    }
}

function download(task) {
    urllib.request(...);
}

getUrlMap(function(err, urlMap) {
    if(err) ...;

    for(const map of urlMap) scarlet.push(map, download);
    scarlet.afterFinish(urlMap.length, function() {
        // finished...
    }, false);
});
```

2018-12-03 05:16 UTC, XadillaX commented
btw, we can use `urllib`'s streaming feature to write a stream to a file stream.

2018-12-07 07:41 UTC, closed without merging